name: immunotyper-methods
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - biopython
  - black
  - flake8
  - ipython
  - jupyter
  - nextflow
  - numpy
  - pandas
  - pathlib
  - pre_commit
  - pytest
  - pytest-cov
  - pytest-mock
  - pytest-xdist
  - python==3.9.19
  - seaborn
  - sphinx
  - sphinx_rtd_theme
  - tqdm
  - samtools
  - awscli
  - bioconda::blast
  - bioconda::bedtools
  - bioconda::minimap2=2.28
  - pysam
  - bioconda::hmmer
  - conda-forge::scikit-learn
  - bioconda::bowtie2
  - freebayes
