name: immunotyper-methods
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core dependencies from benchmark_utils.py
  - python=3.8
  - pandas
  - biopython
  - pathlib
  - samtools
  
  # Workflow management
  - nextflow
  
  # Testing dependencies
  - pytest
  - pytest-cov
  - pytest-mock
  - pytest-xdist
  
  # Development tools
  - ipython
  - jupyter
  - black
  - flake8
  - pre_commit
    
  # Documentation
  - sphinx
  - sphinx_rtd_theme
  
  # Additional useful tools
  - tqdm
  - numpy
  - seaborn